### ISSUE TITLE
关于论文中clip-based模型咨询

### ISSUE THREAD

**Issue by whatever-wlb** [IAAR-Shanghai/FTIIBench#1]
作者您好，看到您的论文非常有启发，但是有如下疑问：
实验中的clip-based模型使用的是BGE相关模型，此模型应该是只支持文本embedding，
是使用bge替换了clip中的语言模型自行重训后的跨模态模型进行的实验吗

**Comment by JCruan519** [comment]
@whatever-wlb 
你好！本文的工作仅聚焦于评估，并没有对BGE进行重新训练。
简单来说，在BGE的评估流程中，获取视觉和语言的embedding，随后计算相似度来决定是否插入图像。
